trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

# Task list https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index?view=azure-devops
steps:
# - task: PowerShell@2
#   displayName: Install LabVIEW NXG
#   inputs:
#     targetType: 'filePath'
#     filePath: '.\AzurePipelines\install.ps1'
# - task: PowerShell@2
#   displayName: Install Trial Window Dependencies
#   inputs:
#     targetType: 'filePath'
#     filePath: '.\AzurePipelines\trialdeps.ps1'
# - task: PowerShell@2
#   displayName: Build LabVIEW Projects
#   inputs:
#     targetType: 'filePath'
#     filePath: '.\AzurePipelines\build.ps1'
- task: PowerShell@2
  displayName: Create GitHub Pages Output
  inputs:
    targetType: 'filePath'
    filePath: '.\AzurePipelines\ghpages.ps1'
- task: CopyFiles@2
  inputs:
    contents: 'ghpagesbuild\ghpages.zip'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ghpages
