trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

# Task list https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index?view=azure-devops
steps:
- task: PowerShell@2
  displayName: Install LabVIEW NXG
  inputs:
    targetType: 'filePath'
    filePath: '.\AzurePipelines\install.ps1'
# - task: UseRubyVersion@0
#   inputs:
#     versionSpec: '>=2.4'
# - task: PowerShell@2
#   displayName: Deploy to gh-pages
#   env: # configuring secrets https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
#     GHPAGESTOKEN: $(ghpagestoken)
#   inputs:
#     targetType: filePath
#     filePath: .\AzurePipelines\ghpagesdeps.ps1
- task: PowerShell@2
  displayName: Build LabVIEW Projects
  inputs:
    targetType: 'filePath'
    filePath: '.\AzurePipelines\build.ps1'
- task: CopyFiles@2
  inputs:
    contents: 'ghpagesbuild\ghpages.zip'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ghpages
