name: webvi-experiments ci

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install LabVIEW NXG
      run: powershell .\AzurePipelines\install.ps1
    - name: Start capturing screenshots
      run: |
        npm install
        npm run start-periodic-screenshot
      working-directory: ./AzurePipelines/periodic-screenshot
    - name: Build LabVIEW Projects
      run: powershell .\AzurePipelines\build.ps1
      timeout-minutes: 30
      continue-on-error: true
    - name: Upload screenshots
      uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: ./AzurePipelines/periodic-screenshot/dist
    - name: Create GitHub Pages Output
      run: powershell .\AzurePipelines\ghpages.ps1
    - name: Upload GitHub Pages Output
      uses: actions/upload-artifact@v1
      with:
        name: ghpagesbuild
        path: /ghpagesbuild
